# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-10 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=10)),
                ('ptm', models.CharField(max_length=255)),
                ('companyName', models.CharField(max_length=255)),
                ('eMail', models.CharField(max_length=250)),
                ('ptmContact', models.CharField(max_length=10)),
            ],
        ),
    ]
