# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='contact',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='ptmContact',
            field=models.IntegerField(max_length=10),
        ),
    ]
